# Generated by Django 2.1.3 on 2018-12-06 13:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateField(default=datetime.datetime(2018, 12, 6, 13, 46, 24, 534423, tzinfo=utc)),
        ),
    ]
