# Generated by Django 2.1.3 on 2018-12-06 16:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20181206_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateField(default=datetime.datetime(2018, 12, 6, 16, 33, 58, 280397, tzinfo=utc)),
        ),
    ]
