# Generated by Django 2.1.3 on 2018-11-11 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_newsletter_list_threshold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter_list',
            name='threshold',
            field=models.CharField(choices=[('free-version', 'FREE'), ('paid-15', '15USD'), ('paid-30', '30USD')], default='free-version', max_length=20),
        ),
        migrations.AlterField(
            model_name='newsletter_list',
            name='user_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
