# Generated by Django 2.1.3 on 2018-12-06 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20181206_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='insta_account',
            name='insta_username',
            field=models.CharField(default='', max_length=30),
        ),
    ]
