# Generated by Django 2.1.3 on 2018-12-07 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_title',
            field=models.TextField(blank=True, default='Blog Title', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='insta_url',
            field=models.URLField(default='https://www.instagram.com/', max_length=1000, null=True),
        ),
    ]
