# Generated by Django 2.1.3 on 2018-12-07 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20181208_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_caption',
            field=models.TextField(blank=True, default='user bio here', max_length=2200, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_slug',
            field=models.SlugField(default='this-is-one', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_post',
            field=models.TextField(default='poace is locked in', max_length=2200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_title',
            field=models.TextField(default='blog post title', max_length=300),
            preserve_default=False,
        ),
    ]
