# Generated by Django 2.1.3 on 2018-12-07 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20181208_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
